# Generated by Django 6.0.1 on 2026-01-22 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('override_type', models.CharField(choices=[('上班', '上班'), ('休息', '休息')], max_length=20, verbose_name='覆盖类型')),
                ('scope', models.CharField(choices=[('全员', '全员'), ('指定组', '指定组'), ('指定人员', '指定人员')], default='全员', max_length=20, verbose_name='作用范围')),
                ('target', models.CharField(blank=True, max_length=200, null=True, verbose_name='目标(组名或人名)')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='原因')),
            ],
            options={
                'verbose_name': '日历覆盖',
                'verbose_name_plural': '日历覆盖',
                'db_table': 'calendar_override',
            },
        ),
        migrations.CreateModel(
            name='GlobalRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_consecutive_work_days', models.IntegerField(default=5)),
                ('max_consecutive_work_days', models.IntegerField(default=6)),
                ('forbidden_rest_days', models.JSONField(default=list)),
                ('allowed_rest_days', models.JSONField(default=list)),
                ('small_week_must_consecutive', models.BooleanField(default=True)),
                ('week_rotation_mode', models.CharField(default='全员同步', max_length=20)),
                ('override_week_rules', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'global_rules',
            },
        ),
        migrations.CreateModel(
            name='GroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_config',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='ShiftDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班次名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'shift_definition',
            },
        ),
        migrations.CreateModel(
            name='SpecialDateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=100)),
                ('is_working_day', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'special_date_rule',
            },
        ),
        migrations.CreateModel(
            name='WeekScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_week', models.JSONField(default=list, help_text='大周休息日列表，0-6代表周一到周日')),
                ('small_week', models.JSONField(default=list, help_text='小周休息日列表，0-6代表周一到周日')),
            ],
            options={
                'verbose_name': '班次大小周配置',
                'verbose_name_plural': '班次大小周配置',
                'db_table': 'week_schedule_config',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('type', models.CharField(choices=[('请假', '请假'), ('病假', '病假'), ('出差', '出差'), ('培训', '培训')], max_length=20, verbose_name='类型')),
                ('count_as_rest', models.BooleanField(default=False, verbose_name='是否算休息')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='原因')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.person', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '请假/不可用',
                'verbose_name_plural': '请假/不可用',
            },
        ),
        migrations.CreateModel(
            name='PersonOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('type', models.CharField(choices=[('必须上班', '必须上班'), ('必须休息', '必须休息')], default='必须上班', max_length=20, verbose_name='锁定类型')),
                ('reason', models.CharField(max_length=200, verbose_name='原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schedule.person', verbose_name='人员')),
            ],
            options={
                'verbose_name': '人员锁定规则',
                'verbose_name_plural': '人员锁定规则',
                'db_table': 'person_override',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='shift_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.shiftdefinition'),
        ),
        migrations.CreateModel(
            name='WeekRotationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('一月', '一月'), ('二月', '二月'), ('三月', '三月'), ('四月', '四月'), ('五月', '五月'), ('六月', '六月'), ('七月', '七月'), ('八月', '八月'), ('九月', '九月'), ('十月', '十月'), ('十一月', '十一月'), ('十二月', '十二月')], max_length=10)),
                ('first_week_type', models.CharField(choices=[('大周', '大周'), ('小周', '小周')], max_length=10)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'week_rotation_config',
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='shiftdefinition',
            name='week_schedule_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_definition', to='Schedule.weekscheduleconfig', verbose_name='大小周配置'),
        ),
    ]
