# Generated by Django 6.0.1 on 2026-01-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftdefinition',
            name='week_schedule_config',
        ),
        migrations.AddField(
            model_name='shiftdefinition',
            name='big_week',
            field=models.JSONField(default=list, help_text='大周工作日列表，0-6代表周一到周日'),
        ),
        migrations.AddField(
            model_name='shiftdefinition',
            name='small_week',
            field=models.JSONField(default=list, help_text='小周工作日列表，0-6代表周一到周日'),
        ),
        migrations.DeleteModel(
            name='WeekScheduleConfig',
        ),
    ]
