# Generated by Django 6.0.1 on 2026-01-22 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_remove_shiftdefinition_week_schedule_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalRules',
        ),
    ]
