# Generated by Django 6.0.1 on 2026-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0005_add_calendaroverride_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaroverride',
            name='target',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='目标(组名或人员)'),
        ),
    ]
