# Generated by Django 6.0.1 on 2026-01-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0009_update_shift_rotation_group_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrotationgroup',
            name='even_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_group_even', to='Schedule.shiftdefinition', verbose_name='偶数月班次'),
        ),
        migrations.AlterField(
            model_name='shiftrotationgroup',
            name='odd_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_group_odd', to='Schedule.shiftdefinition', verbose_name='奇数月班次'),
        ),
    ]
