# Generated by Django 6.0.1 on 2026-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0010_alter_shiftrotationgroup_even_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID'),
        ),
    ]
