# Generated by Codex on 2026-01-23

from django.db import migrations, models
import django.db.models.deletion


def map_group_names(apps, schema_editor):
    Person = apps.get_model('Schedule', 'Person')
    GroupConfig = apps.get_model('Schedule', 'GroupConfig')
    group_map = {group.name: group.id for group in GroupConfig.objects.all()}
    for person in Person.objects.all():
        if person.group and person.group in group_map:
            person.group_fk_id = group_map[person.group]
            person.save(update_fields=['group_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0011_person_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schedule.groupconfig'),
        ),
        migrations.RunPython(map_group_names, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='person',
            name='group',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='group_fk',
            new_name='group',
        ),
    ]
